### ISSUE TITLE
Execute StarCraft individuals

### ISSUE THREAD

**Issue by fergunet** [geneura-papers/2015-ECTA#10]
- 30 runs per individual
- 10 individuals 
- At gen 1, gen 15 and gen 30 (last one).

**Comment by JJ** [comment]
:+1:

**Comment by fergunet** [comment]
@JJ btw, is there any deadline for this? Was the paper invited to the Special Issue, as with the Ephemech proposal?

**Comment by JJ** [comment]
It was, but no deadlie for the time being. Just do it ASAP :-)

**Comment by fergunet** [comment]
I've added the current execution data (they are still running in 3 computers).
-4 individuals, 30 times for Gen1
-3 individuals, 30 times for Gen15
-3 individuals, 30 times (except the last one, 26) for Gen 15

Tomorrow morning I will add the last 4 runs for the last individual in Gen 15 (or new complete runs of individuals if they are avaible, but I think it will be complicated...).

CSVs are in the form
INDIVIDUAL_ID: (example: individualB.cpp)
#EVALUATION: (from 0 to 29)
VICTORIES_AGAINST_STRONGEST_TIER: (3, 6, 9 or 12)
VICTORIES_AGAINST_MEDIUM_TIER: (3, 6, 9 or 12)
VICTORIES_AGAINST_WEAKEST_TIER: (3, 6, 9 or 12)
SCORE_RATIO: (example 0.001231313)
AGGREGATED: (example 5.001231313)

Initially we gave 3 points per victory in the CIG paper (that is why columns in STRONGEST MEDIUM WEAKEST have multiples of 3) but I used the formula in the current paper to generate a double fitness (Column AGGREGATED) taking into account the number of victories in each tier+the score ratio. So, @JJ focus only in the last column, if you want.
