### ISSUE TITLE
Crear repo para el artículo y ponerlo allí con formato correcto

### ISSUE THREAD

**Issue by amorag** [geneura-papers/2015-ECTA#11]
Habría que hacer un repo del artículo extendido y ponerlo en el formato de la revista, que no sé cuál es.
He buscado por 'TCCI' y me aparecen libros de Springer...

**Comment by JJ** [comment]
Se va a hacer en el mismo repo. Ya está etiquetado como 0.99 la versión del congreso, se sigue trabajando a partir de ahí. El formato es el mismo.
