### ISSUE TITLE
Propose new title

### ISSUE THREAD

**Issue by JJ** [geneura-papers/2015-ECTA#13]
Should be different. Please all help suggesting on the text itself.

**Comment by ccottap** [comment]
Hay un 'in' repetido. Posible título alternativo
"The Uncertainty Quandary: A Study in the Context of the Evolutionary Optimization of Games"

**Comment by JJ** [comment]
Me gusta.

2016-01-15 11:38 GMT+01:00 Carlos Cotta notifications@github.com:

> Hay un 'in' repetido. Posible título alternativo
> "The Uncertainty Quandary: A Study in the Context of the Evolutionary
> Optimization of Games"
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2015-ECTA/issues/13#issuecomment-171929660
> .

## 

JJ

**Comment by amorag** [comment]
Yo puse otra propuesta en el tex directamente.

Es "Noise plays: a study of uncertainty in the context of evolutionary optimization in games"
Queriendo decir (aunque quizá de forma incorrecta :() que 'el ruido juega', que participa en el proceso. ;)

En todo caso, yo no diría "of Games", no se evolucionan los juegos, sino aspectos de ellos.
Yo diría "in Games", sea cual sea el título. ;D

**Comment by JJ** [comment]
Es que no me gusta hablar de noise, porque se lía todo...

**Comment by amorag** [comment]
Ok, me parece bien.
Pero vaya, que lo de 'noise' lo pusiste tú en el título inicial. XD

En todo caso repito, yo pondría 'in games' en lugar de 'of games' por lo que he comentado arriba.

Además, si se meten resultados de MLPs quitaría lo de los juegos del título y pondría algo como 'uncertain problems' o algo similar que esté bien escrito. :D
