### ISSUE TITLE
Training neural networks?

### ISSUE THREAD

**Issue by JJ** [geneura-papers/2015-ECTA#17]
Can we have the results of training a neural network, which should be noisy or uncertain?
Can you make this? 30-100 evaluations of 10 individuals in generation 1 one in the middle, and one in the end?

**Comment by pacastillo** [comment]
What kind of ANN do you want to use?

**Comment by JJ** [comment]
Any one would do, as long as its result is variable. If your GProp is still working, it would be perfect.

**Comment by pacastillo** [comment]
Yes, we can use the MLP.
Where is the data file?

**Comment by amorag** [comment]
If you finally add these data and results, which I think would be good for the paper, I guess the title should be changed. ;)
