### ISSUE TITLE
Decide termination condition paper objectives

### ISSUE THREAD

**Issue by JJ** [geneura-papers/2015-ECTA#2]
What do we want to prove this time? 
Anyone can participate, including @amorag @pacastillo

**Comment by elimail** [comment]
Use hypervolume metric to evaluate different stop conditions

**Comment by JJ** [comment]
In general, evaluate different ways of comparing termination conditions.

**Comment by pacastillo** [comment]
We should enumerate and describe in detail the different termination conditions, and then the hypervolume should be introduced.
