### ISSUE TITLE
Discuss additions to the paper

### ISSUE THREAD

**Issue by JJ** [geneura-papers/2015-ECTA#9]
What can we do with the new paper? Can we obtain new data? Are there new problems we could work with? Should we test a real evolutionary algorithm using that model as we did las year? Any idea?

**Comment by amorag** [comment]
What is the Special Issue TCCI about?

We could have data, for instance, from the evolution of UnrealBots and StarCraft, I guess.
But what would be the aim of the new paper? An extension of the ECTA paper or a new approach?

**Comment by JJ** [comment]
2015-12-23 20:56 GMT+01:00 Antonio Mora notifications@github.com:

> What is the Special Issue TCCI about?
> 
> We could have data, for instance, from the evolution of UnrealBots and
> StarCraft, I guess.
> But what would be the aim of the new paper? An extension of the ECTA paper
> or a new approach?

Estension. @fergunet, can we obtain StarCratft data? Do you have UnrealBots
data?

JJ

**Comment by fergunet** [comment]
Yes, I have the logs of several runs of the Starcraft thing, we can add
them :)

2015-12-24 9:20 GMT+01:00 Juan Julián Merelo Guervós <
notifications@github.com>:

> 2015-12-23 20:56 GMT+01:00 Antonio Mora notifications@github.com:
> 
> > What is the Special Issue TCCI about?
> > 
> > We could have data, for instance, from the evolution of UnrealBots and
> > StarCraft, I guess.
> > But what would be the aim of the new paper? An extension of the ECTA
> > paper
> > or a new approach?
> 
> Estension. @fergunet, can we obtain StarCratft data? Do you have UnrealBots
> data?
> 
> JJ
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/geneura-papers/2015-ECTA/issues/9#issuecomment-167066709
> .

## 

Dr. Pablo García Sánchez
University of Granada
http://www.ugr.es/~pablogarcia

**Comment by JJ** [comment]
Hi,

2015-12-24 15:10 GMT+01:00 Pablo García Sánchez notifications@github.com:

> Yes, I have the logs of several runs of the Starcraft thing, we can add
> them :)

If possible, we would need > 30 evaluations of at least 10 individuals in
the first generatio, another generation later on, and another one by the
end of the run. Is that possible?

**Comment by amorag** [comment]
What is the special issue TCCI about?
To see the aim of the work.

**Comment by JJ** [comment]
Selected papers from ECTA.
